import { Route } from "react-router"

import Level, { type LevelProps } from "../pages/level/Level"
import LevelCreator from "../pages/levelCreator/LevelCreator"
import paths from "./paths"

const levels = [
  {
    id: 1,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards"],
  },
  {
    id: 2,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards"],
  },
  {
    id: 3,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right"],
  },
  {
    id: 4,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_left"],
  },
  {
    id: 5,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 6,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 7,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 8,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 9,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 10,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 11,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 12,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 13,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 14,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 15,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "deliver",
    ],
  },
  {
    id: 16,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "deliver",
    ],
  },
  {
    id: 17,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "deliver",
    ],
  },
  {
    id: 18,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "deliver",
    ],
  },
  {
    id: 19,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 20,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 21,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 22,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 23,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 24,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 25,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 26,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 27,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 28,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 29,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "at_destination",
      "repeat_until",
    ],
  },
  {
    id: 30,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "at_destination",
      "repeat_until",
    ],
  },
  {
    id: 31,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "at_destination",
      "repeat_until",
    ],
  },
  {
    id: 32,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "at_destination",
      "repeat_until",
    ],
  },
  {
    id: 33,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_if",
      "at_destination",
      "road_exists",
      "repeat_until",
    ],
  },
  {
    id: 34,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_if",
      "at_destination",
      "road_exists",
      "repeat_until",
    ],
  },
  {
    id: 35,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_if",
      "at_destination",
      "road_exists",
      "repeat_until",
    ],
  },
  {
    id: 36,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_if",
      "at_destination",
      "road_exists",
      "repeat_until",
    ],
  },
  {
    id: 37,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_if",
      "at_destination",
      "road_exists",
      "repeat_until",
    ],
  },
  {
    id: 38,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "sound_horn",
      "controls_if",
      "at_destination",
      "road_exists",
      "cow_crossing",
      "repeat_until",
    ],
  },
  {
    id: 39,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "turn_around",
      "sound_horn",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "cow_crossing",
      "controls_repeat",
      "repeat_until",
    ],
  },
  {
    id: 40,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "turn_around",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "controls_repeat",
      "repeat_until",
    ],
  },
  {
    id: 41,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "turn_around",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "controls_repeat",
      "repeat_until",
    ],
  },
  {
    id: 42,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "turn_around",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "controls_repeat",
      "repeat_until",
    ],
  },
  {
    id: 43,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "turn_around",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "controls_repeat",
      "repeat_until",
    ],
  },
  {
    id: 44,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "wait",
      "controls_if",
      "at_destination",
      "road_exists",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 45,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "wait",
      "controls_if",
      "at_destination",
      "road_exists",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 46,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "wait",
      "controls_if",
      "at_destination",
      "road_exists",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 47,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "sound_horn",
      "controls_if",
      "at_destination",
      "road_exists",
      "cow_crossing",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 48,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "turn_around",
      "wait",
      "deliver",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 49,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "turn_around",
      "wait",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 50,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "turn_around",
      "wait",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 51,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      ["turn_left", 2],
      ["turn_right", 3],
    ],
  },
  {
    id: 52,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["turn_left", 2],
      ["turn_right", 2],
      "controls_repeat",
    ],
  },
  {
    id: 53,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 2],
      ["turn_left", 3],
      ["turn_right", 2],
      "controls_repeat",
    ],
  },
  {
    id: 54,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["turn_left", 2],
      ["turn_right", 1],
      "controls_repeat",
    ],
  },
  {
    id: 55,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["turn_left", 1],
      ["turn_right", 1],
      "controls_if",
      "at_destination",
      ["road_exists", 1],
      "repeat_until",
    ],
  },
  {
    id: 56,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      "controls_if",
      "at_destination",
      ["road_exists", 2],
      "repeat_until",
    ],
  },
  {
    id: 57,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      "controls_if",
      ["logic_negate", 1],
      ["at_destination", 1],
      ["road_exists", 2],
      "repeat_while",
    ],
  },
  {
    id: 58,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 2],
      ["turn_left", 1],
      ["turn_right", 1],
      ["logic_negate", 1],
      ["at_destination", 1],
      ["controls_repeat", 4],
      "repeat_while",
    ],
  },
  {
    id: 59,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["turn_left", 2],
      ["turn_around", 1],
      ["at_destination", 1],
      ["repeat_until", 1],
    ],
  },
  {
    id: 60,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_right", 1],
      ["turn_around", 1],
      "controls_repeat",
    ],
  },
  {
    id: 61,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
      "procedures_defnoreturn",
      "controls_repeat",
    ],
  },
  {
    id: 62,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "wait",
      "at_destination",
      "traffic_light",
      "procedures_callnoreturn",
      "procedures_defnoreturn",
      "repeat_until",
    ],
  },
  {
    id: 63,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
      "procedures_defnoreturn",
    ],
  },
  {
    id: 64,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
      "procedures_defnoreturn",
      "controls_repeat",
    ],
  },
  {
    id: 65,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
      "procedures_defnoreturn",
      "controls_repeat",
    ],
  },
  {
    id: 66,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
      "procedures_defnoreturn",
      "controls_repeat",
    ],
  },
  {
    id: 67,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
      "procedures_defnoreturn",
      "controls_repeat",
    ],
  },
  {
    id: 68,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 2],
      ["turn_left", 1],
      ["turn_around", 1],
      "road_exists",
      ["dead_end", 1],
      "repeat_while",
    ],
  },
  {
    id: 69,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 2],
      ["turn_left", 1],
      "turn_right",
      ["turn_around", 2],
      ["wait", 1],
      "road_exists",
      ["dead_end", 1],
      "repeat_while",
    ],
  },
  {
    id: 70,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["turn_left", 1],
      ["turn_right", 2],
      ["turn_around", 1],
      ["at_destination", 1],
      "repeat_while",
      ["repeat_until", 1],
    ],
  },
  {
    id: 71,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      "controls_if",
      "at_destination",
      ["road_exists", 1],
      "repeat_until",
    ],
  },
  {
    id: 72,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      ["turn_around", 2],
      "at_destination",
      "road_exists",
      ["repeat_until", 2],
    ],
  },
  {
    id: 73,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      ["wait", 1],
      "controls_if",
      "road_exists",
      "dead_end",
      "traffic_light",
      "procedures_callnoreturn",
      "procedures_defnoreturn",
      "repeat_until",
    ],
  },
  {
    id: 74,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 2],
      ["turn_right", 1],
      ["turn_around", 2],
      "procedures_callnoreturn",
      "procedures_defnoreturn",
      ["controls_repeat", 1],
    ],
  },
  {
    id: 75,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      "logic_negate",
      "road_exists",
      "dead_end",
      ["controls_repeat", 1],
      "repeat_until",
    ],
  },
  {
    id: 76,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_right", 3],
      "wait",
      "controls_if",
      "logic_negate",
      "at_destination",
      "road_exists",
      ["repeat_while", 1],
    ],
  },
  {
    id: 77,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      "wait",
      "controls_if",
      "road_exists",
      "procedures_callnoreturn",
      ["procedures_defnoreturn", 2],
    ],
  },
  {
    id: 78,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 2],
      "turn_left",
      ["turn_right", 1],
      ["turn_around", 3],
      ["logic_negate", 1],
      ["at_destination", 1],
      ["road_exists", 2],
      ["dead_end", 2],
      ["repeat_while", 4],
      ["repeat_until", 1],
    ],
  },
  {
    id: 79,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 7],
      ["turn_left", 4],
      ["turn_right", 1],
      "controls_if",
      "logic_negate",
      "road_exists",
      "procedures_callnoreturn",
      ["procedures_defnoreturn", 1],
    ],
  },
  {
    id: 80,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 81,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 82,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 83,
    mode: "python",
    commands: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 84,
    mode: "python",
    commands: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 85,
    mode: "python",
    commands: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 86,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "controls_whileUntil",
      "variables_set",
      "math_change",
      "variables_get",
      "math_number",
      "logic_compare",
    ],
  },
  {
    id: 87,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "controls_whileUntil",
      "variables_set",
      "math_change",
      "variables_get",
      "math_number",
      "logic_compare",
    ],
  },
  {
    id: 88,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "controls_whileUntil",
      "variables_set",
      "math_change",
      "variables_get",
      "math_number",
      "logic_compare",
    ],
  },
  {
    id: 89,
    mode: "python",
    commands: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 90,
    mode: "python",
    commands: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 91,
    mode: "python",
    commands: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 92,
    mode: "python",
    commands: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 93,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "sound_horn",
      "controls_if",
      "cow_crossing",
      "controls_whileUntil",
      "variables_set",
      "math_change",
      "variables_get",
      "math_number",
      "logic_compare",
    ],
  },
  {
    id: 94,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "controls_if",
      "road_exists",
      "controls_whileUntil",
      "variables_set",
      "math_change",
      "variables_get",
      "math_number",
      "logic_compare",
    ],
  },
  {
    id: 95,
    mode: "python",
    commands: ["turn_left", "turn_right", "is_animal_crossing", "sound_horn"],
  },
  {
    id: 96,
    mode: "python",
    commands: ["move_forwards", "turn_left", "turn_right", "is_road_left"],
  },
  {
    id: 97,
    mode: "python",
    commands: ["move_forwards", "turn_left", "is_road_left"],
  },
  {
    id: 98,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "controls_if",
      "road_exists",
      "controls_whileUntil",
      "variables_set",
      "math_change",
      "variables_get",
      "math_number",
      "logic_compare",
    ],
  },
  {
    id: 99,
    mode: "python",
    commands: ["turn_left", "turn_right", "is_road_left"],
  },
  {
    id: 100,
    mode: "python",
    commands: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "deliver",
      "is_road_left",
    ],
  },
  {
    id: 101,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "controls_if",
      "road_exists",
      "controls_whileUntil",
      "variables_set",
      "math_change",
      "variables_get",
      "math_number",
      "logic_compare",
    ],
  },
  {
    id: 102,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "controls_if",
      "road_exists",
      "controls_whileUntil",
      "variables_set",
      "math_change",
      "variables_get",
      "math_number",
      "logic_compare",
    ],
  },
  {
    id: 103,
    mode: "python",
    commands: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "is_road_forward",
      "is_road_left",
    ],
  },
  {
    id: 104,
    mode: "python",
    commands: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "wait",
      "is_road_forward",
      "is_road_left",
      "at_red_traffic_light",
    ],
  },
  {
    id: 105,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "logic_negate",
      "at_destination",
      "controls_whileUntil",
    ],
  },
  {
    id: 106,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "logic_negate",
      "at_destination",
      "controls_whileUntil",
    ],
  },
  {
    id: 107,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "turn_left",
      "turn_right",
      "logic_negate",
      "at_destination",
      "controls_whileUntil",
    ],
  },
  {
    id: 108,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "logic_negate",
      "at_destination",
      "controls_whileUntil",
    ],
  },
  {
    id: 109,
    mode: "python",
    commands: ["turn_left", "turn_right", "at_destination"],
  },
  {
    id: 110,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "controls_if",
      "logic_negate",
      "at_destination",
      "road_exists",
      "controls_whileUntil",
    ],
  },
  {
    id: 111,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "controls_if",
      "logic_negate",
      "at_destination",
      "road_exists",
      "controls_whileUntil",
    ],
  },
  {
    id: 112,
    mode: "python",
    commands: ["turn_left", "turn_right", "is_road_left", "at_destination"],
  },
  {
    id: 113,
    mode: "python",
    commands: [
      "move_forwards",
      "turn_right",
      "is_road_right",
      "at_destination",
    ],
  },
  {
    id: 114,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "controls_if",
      "logic_negate",
      "at_destination",
      "road_exists",
      "controls_whileUntil",
    ],
  },
  {
    id: 115,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "sound_horn",
      "controls_if",
      "logic_negate",
      "at_destination",
      "road_exists",
      "cow_crossing",
      "controls_whileUntil",
    ],
  },
  {
    id: 116,
    mode: "python",
    commands: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "at_destination",
      "is_road_forward",
      "is_road_right",
      "is_road_left",
    ],
  },
  {
    id: 117,
    mode: "python",
    commands: [
      "move_forwards",
      "turn_around",
      "turn_right",
      "at_destination",
      "is_road_forward",
      "at_dead_end",
      "is_animal_crossing",
      "sound_horn",
    ],
  },
  {
    id: 118,
    mode: "python",
    commands: [
      "move_forwards",
      "turn_left",
      "at_destination",
      "is_road_forward",
      "is_animal_crossing",
      "sound_horn",
    ],
  },
  {
    id: 119,
    mode: "python",
    commands: [
      "move_forwards",
      "turn_around",
      "turn_left",
      "turn_right",
      "wait",
      "deliver",
      "at_red_traffic_light",
      "at_destination",
      "is_road_forward",
      "is_road_left",
      "is_road_right",
      "at_dead_end",
    ],
  },
  {
    id: 120,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "controls_repeat",
    ],
  },
  {
    id: 121,
    mode: "python",
    commands: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 122,
    mode: "python",
    commands: ["move_forwards", "turn_left"],
  },
  {
    id: 123,
    mode: "blocklyAndPython",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "controls_repeat",
    ],
  },
  {
    id: 124,
    mode: "python",
    commands: ["move_forwards", "turn_left", "turn_right"],
  },
  {
    id: 125,
    mode: "python",
    commands: ["move_forwards", "turn_right", "at_destination"],
  },
  {
    id: 126,
    mode: "python",
    commands: ["move_forwards", "turn_left", "at_destination"],
  },
  {
    id: 127,
    mode: "python",
    commands: ["move_forwards", "turn_left", "at_destination"],
  },
  {
    id: 128,
    mode: "python",
    commands: ["move_forwards", "turn_right", "turn_left", "at_destination"],
  },
] as const satisfies LevelProps[]

export default (
  <>
    <Route path={paths.level.creator._} element={<LevelCreator />} />
    {levels.map(({ id, ...levelProps }) => (
      <Route
        key={`level-${id}`}
        path={paths.level.id[id]._}
        element={<Level id={id} {...levelProps} />}
      />
    ))}
    <Route path={paths.level.id._} element={<Level />} />
  </>
)
