import { Route } from "react-router"

import Level, { type LevelProps } from "../pages/level/Level"
import LevelCreator from "../pages/levelCreator/LevelCreator"
import paths from "./paths"

const levels = [
  {
    id: 1,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards"],
  },
  {
    id: 2,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards"],
  },
  {
    id: 3,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right"],
  },
  {
    id: 4,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right"],
  },
  {
    id: 5,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 6,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 7,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 8,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 9,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 10,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 11,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 12,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 13,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 14,
    mode: "blockly",
    blockly_toolbox_block_types: ["move_forwards", "turn_right", "turn_left"],
  },
  {
    id: 15,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "deliver",
    ],
  },
  {
    id: 16,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "deliver",
    ],
  },
  {
    id: 17,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "deliver",
    ],
  },
  {
    id: 18,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "deliver",
    ],
  },
  {
    id: 19,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 20,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 21,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 22,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 23,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 24,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 25,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 26,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 27,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 28,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_repeat",
    ],
  },
  {
    id: 29,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "at_destination",
      "controls_whileUntil",
    ],
  },
  {
    id: 30,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "at_destination",
      "controls_whileUntil",
    ],
  },
  {
    id: 31,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "at_destination",
      "controls_whileUntil",
    ],
  },
  {
    id: 32,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "at_destination",
      "controls_whileUntil",
    ],
  },
  {
    id: 33,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_if",
      "at_destination",
      "road_exists",
      "controls_whileUntil",
    ],
  },
  {
    id: 34,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_if",
      "at_destination",
      "road_exists",
      "controls_whileUntil",
    ],
  },
  {
    id: 35,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_if",
      "at_destination",
      "road_exists",
      "controls_whileUntil",
    ],
  },
  {
    id: 36,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_if",
      "at_destination",
      "road_exists",
      "controls_whileUntil",
    ],
  },
  {
    id: 37,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "controls_if",
      "at_destination",
      "road_exists",
      "controls_whileUntil",
    ],
  },
  {
    id: 38,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "sound_horn",
      "controls_if",
      "at_destination",
      "road_exists",
      "cow_crossing",
      "controls_whileUntil",
    ],
  },
  {
    id: 39,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "turn_around",
      "sound_horn",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "cow_crossing",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 40,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "turn_around",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 41,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "turn_around",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 42,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "turn_around",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 43,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "turn_left",
      "turn_around",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 44,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "wait",
      "controls_if",
      "at_destination",
      "road_exists",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 45,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "wait",
      "controls_if",
      "at_destination",
      "road_exists",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 46,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_right",
      "wait",
      "controls_if",
      "at_destination",
      "road_exists",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 47,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "sound_horn",
      "controls_if",
      "at_destination",
      "road_exists",
      "cow_crossing",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 48,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "turn_around",
      "wait",
      "deliver",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 49,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "turn_around",
      "wait",
      "deliver",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 50,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "turn_around",
      "wait",
      "deliver",
      "controls_if",
      "at_destination",
      "road_exists",
      "dead_end",
      "traffic_light",
      "controls_repeat",
      "controls_whileUntil",
    ],
  },
  {
    id: 51,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      ["turn_left", 3],
      ["turn_right", 2],
    ],
  },
  {
    id: 52,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["turn_left", 2],
      ["turn_right", 2],
      "controls_repeat",
    ],
  },
  {
    id: 53,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 2],
      ["turn_left", 3],
      ["turn_right", 2],
      "controls_repeat",
    ],
  },
  {
    id: 54,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["turn_left", 2],
      ["turn_right", 1],
      "controls_repeat",
    ],
  },
  {
    id: 55,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["turn_left", 1],
      ["turn_right", 1],
      "controls_if",
      "at_destination",
      ["road_exists", 1],
      "controls_whileUntil",
    ],
  },
  {
    id: 56,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      "controls_if",
      "at_destination",
      ["road_exists", 2],
      "controls_whileUntil",
    ],
  },
  {
    id: 57,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      "controls_if",
      ["logic_negate", 1],
      ["at_destination", 1],
      ["road_exists", 2],
      "controls_whileUntil",
    ],
  },
  {
    id: 58,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 2],
      ["turn_left", 1],
      ["turn_right", 1],
      ["logic_negate", 1],
      ["at_destination", 1],
      ["controls_repeat", 4],
      "controls_whileUntil",
    ],
  },
  {
    id: 59,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["turn_left", 2],
      ["turn_around", 1],
      ["at_destination", 1],
      ["controls_whileUntil", 1],
    ],
  },
  {
    id: 60,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_right", 1],
      ["turn_around", 1],
      "controls_repeat",
    ],
  },
  {
    id: 61,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
      "controls_repeat",
    ],
  },
  {
    id: 62,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "wait",
      "at_destination",
      "traffic_light",
      "procedures_callnoreturn",
      "controls_whileUntil",
    ],
  },
  {
    id: 63,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
    ],
  },
  {
    id: 64,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
      "controls_repeat",
    ],
  },
  {
    id: 65,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
      "controls_repeat",
    ],
  },
  {
    id: 66,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
      "controls_repeat",
    ],
  },
  {
    id: 67,
    mode: "blockly",
    blockly_toolbox_block_types: [
      "move_forwards",
      "turn_left",
      "turn_right",
      "procedures_callnoreturn",
      "controls_repeat",
    ],
  },
  {
    id: 68,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 2],
      ["turn_left", 1],
      ["turn_around", 1],
      "road_exists",
      ["dead_end", 1],
      "controls_whileUntil",
    ],
  },
  {
    id: 69,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 2],
      ["turn_left", 1],
      "turn_right",
      ["turn_around", 2],
      ["wait", 1],
      "road_exists",
      ["dead_end", 1],
      "controls_whileUntil",
    ],
  },
  {
    id: 70,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["turn_left", 1],
      ["turn_right", 2],
      ["turn_around", 1],
      ["at_destination", 1],
      ["controls_whileUntil", 1],
    ],
  },
  {
    id: 71,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      "controls_if",
      "at_destination",
      ["road_exists", 1],
      "controls_whileUntil",
    ],
  },
  {
    id: 72,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      ["turn_around", 2],
      "at_destination",
      "road_exists",
      ["controls_whileUntil", 2],
    ],
  },
  {
    id: 73,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      ["wait", 1],
      "controls_if",
      "road_exists",
      "dead_end",
      "traffic_light",
      "procedures_callnoreturn",
      "controls_whileUntil",
    ],
  },
  {
    id: 74,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 2],
      ["turn_right", 1],
      ["turn_around", 2],
      "procedures_callnoreturn",
      ["controls_repeat", 1],
    ],
  },
  {
    id: 75,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      ["turn_right", 1],
      "logic_negate",
      "road_exists",
      "dead_end",
      ["controls_repeat", 1],
      "controls_whileUntil",
    ],
  },
  {
    id: 76,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_right", 3],
      "wait",
      "controls_if",
      "logic_negate",
      "at_destination",
      "road_exists",
      ["controls_whileUntil", 1],
    ],
  },
  {
    id: 77,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 1],
      ["turn_left", 1],
      "wait",
      "controls_if",
      "road_exists",
      "procedures_callnoreturn",
      ["procedures_defnoreturn", 2],
    ],
  },
  {
    id: 78,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 2],
      "turn_left",
      ["turn_right", 1],
      ["turn_around", 3],
      ["logic_negate", 1],
      ["at_destination", 1],
      ["road_exists", 2],
      ["dead_end", 2],
      ["controls_whileUntil", 5],
    ],
  },
  {
    id: 79,
    mode: "blockly",
    blockly_toolbox_block_types: [
      ["move_forwards", 7],
      ["turn_left", 4],
      ["turn_right", 1],
      "controls_if",
      "logic_negate",
      "road_exists",
      "procedures_callnoreturn",
      ["procedures_defnoreturn", 1],
    ],
  },
] as const satisfies LevelProps[]

export default (
  <>
    <Route path={paths.level.creator._} element={<LevelCreator />} />
    {levels.map(({ id, ...levelProps }) => (
      <Route
        key={`level-${id}`}
        path={paths.level.id[id]._}
        element={<Level id={id} {...levelProps} />}
      />
    ))}
    <Route path={paths.level.id._} element={<Level />} />
  </>
)
