import { CloudDownload as CloudDownloadIcon } from "@mui/icons-material"
import { type FC } from "react"

import {
  ButtonItem,
  type ButtonItemProps,
} from "../../../components/miniDrawers"
import { usePhaserGameContext } from "../../../app/hooks"

const exampleLevelTiledJson = {
  orientation: "orthogonal",
  renderorder: "right-down",
  version: 1,
  nextobjectid: 0,
  width: 10,
  height: 8,
  tilewidth: 64,
  tileheight: 64,
  properties: [
    {
      name: "background",
      type: "string",
      value: "GRASS",
    },
  ],
  tilesets: [
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 2,
      image: "http://localhost:5173/src/phaser/tilesets/road/asphalt/turn.svg",
      name: "http://localhost:5173/src/phaser/tilesets/road/asphalt/turn.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      properties: [
        {
          name: "canDriveForwards",
          value: false,
          type: "bool",
        },
        {
          name: "canDriveBackwards",
          value: false,
          type: "bool",
        },
        {
          name: "canTurnLeft",
          value: true,
          type: "bool",
        },
        {
          name: "canTurnRight",
          value: true,
          type: "bool",
        },
      ],
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 1,
      image:
        "http://localhost:5173/src/phaser/tilesets/road/asphalt/straight.svg",
      name: "http://localhost:5173/src/phaser/tilesets/road/asphalt/straight.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      properties: [
        {
          name: "canDriveForwards",
          value: true,
          type: "bool",
        },
        {
          name: "canDriveBackwards",
          value: true,
          type: "bool",
        },
        {
          name: "canTurnLeft",
          value: false,
          type: "bool",
        },
        {
          name: "canTurnRight",
          value: false,
          type: "bool",
        },
      ],
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 5,
      image:
        "http://localhost:5173/src/phaser/tilesets/road/asphalt/dead_end.svg",
      name: "http://localhost:5173/src/phaser/tilesets/road/asphalt/dead_end.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      properties: [
        {
          name: "canDriveForwards",
          value: false,
          type: "bool",
        },
        {
          name: "canDriveBackwards",
          value: true,
          type: "bool",
        },
        {
          name: "canTurnLeft",
          value: false,
          type: "bool",
        },
        {
          name: "canTurnRight",
          value: false,
          type: "bool",
        },
      ],
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 3,
      image:
        "http://localhost:5173/src/phaser/tilesets/road/asphalt/t_junction.svg",
      name: "http://localhost:5173/src/phaser/tilesets/road/asphalt/t_junction.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      properties: [
        {
          name: "canDriveForwards",
          value: false,
          type: "bool",
        },
        {
          name: "canDriveBackwards",
          value: true,
          type: "bool",
        },
        {
          name: "canTurnLeft",
          value: true,
          type: "bool",
        },
        {
          name: "canTurnRight",
          value: true,
          type: "bool",
        },
      ],
    },
    {
      imagewidth: 32,
      imageheight: 32,
      tilewidth: 32,
      tileheight: 32,
      firstgid: 24,
      image:
        "http://localhost:5173/src/phaser/tilesets/endpoints/house/common/orange.svg",
      name: "http://localhost:5173/src/phaser/tilesets/endpoints/house/common/orange.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 18,
      image:
        "http://localhost:5173/src/phaser/tilesets/endpoints/cfc/warehouse/default.svg",
      name: "http://localhost:5173/src/phaser/tilesets/endpoints/cfc/warehouse/default.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 29,
      image:
        "http://localhost:5173/src/phaser/tilesets/scenery/building/school.svg",
      name: "http://localhost:5173/src/phaser/tilesets/scenery/building/school.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      imagescale: 0.2,
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 45,
      image:
        "http://localhost:5173/src/phaser/tilesets/scenery/other/solar_panel.svg",
      name: "http://localhost:5173/src/phaser/tilesets/scenery/other/solar_panel.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      imagescale: 0.2,
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 39,
      image:
        "http://localhost:5173/src/phaser/tilesets/scenery/nature/tree/pine.svg",
      name: "http://localhost:5173/src/phaser/tilesets/scenery/nature/tree/pine.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      imagescale: 0.65,
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 37,
      image:
        "http://localhost:5173/src/phaser/tilesets/scenery/nature/pond.svg",
      name: "http://localhost:5173/src/phaser/tilesets/scenery/nature/pond.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      imagescale: 0.3,
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 35,
      image:
        "http://localhost:5173/src/phaser/tilesets/scenery/nature/crops.svg",
      name: "http://localhost:5173/src/phaser/tilesets/scenery/nature/crops.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      imagescale: 0.3,
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 34,
      image:
        "http://localhost:5173/src/phaser/tilesets/scenery/nature/bush.svg",
      name: "http://localhost:5173/src/phaser/tilesets/scenery/nature/bush.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      imagescale: 0.5,
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 26,
      image:
        "http://localhost:5173/src/phaser/tilesets/scenery/building/hospital.svg",
      name: "http://localhost:5173/src/phaser/tilesets/scenery/building/hospital.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      imagescale: 0.125,
    },
    {
      imagewidth: 64,
      imageheight: 64,
      tilewidth: 64,
      tileheight: 64,
      firstgid: 27,
      image:
        "http://localhost:5173/src/phaser/tilesets/scenery/building/house.svg",
      name: "http://localhost:5173/src/phaser/tilesets/scenery/building/house.svg",
      tilecount: 1,
      columns: 1,
      spacing: 0,
      margin: 0,
      imagescale: 0.1,
    },
  ],
  layers: [
    {
      x: 0,
      y: 0,
      width: 10,
      height: 8,
      opacity: 1,
      visible: true,
      name: "Tile.ROAD",
      type: "tilelayer",
      data: [
        1610612738, -1610612735, -1610612731, 1610612741, 1610612739,
        -1610612731, 1610612738, -1610612731, 1610612738, -1610612731,
        -1073741822, -1610612735, 2, 0, 1, 0, -1073741821, -1610612731,
        -1073741821, -1610612731, 1610612741, -1610612735, -1610612734, 0,
        -1073741819, 0, -1073741822, -1610612731, -1073741819, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1610612738, -1610612731, 5,
        0, 1610612738, -1610612735, 2, 1610612738, -1610612735, 2, -1073741821,
        -1610612731, 1, 0, 1, 0, 1, -1073741821, 1610612739, -1610612734,
        -1073741819, 0, -1073741822, -1610612731, -1073741822, -1610612735,
        -1610612734, -1073741819, -1073741822, -1610612731,
      ],
    },
    {
      x: 0,
      y: 0,
      width: 10,
      height: 8,
      opacity: 1,
      visible: true,
      name: "ObjectGroup.OBSTACLES",
      type: "objectgroup",
      draworder: "topdown",
      objects: [],
    },
    {
      x: 0,
      y: 0,
      width: 10,
      height: 8,
      opacity: 1,
      visible: true,
      name: "ObjectGroup.ENDPOINTS",
      type: "objectgroup",
      draworder: "topdown",
      objects: [
        {
          id: 1,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 81.6,
          y: 46.4,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "top",
            },
            {
              name: "tileRow",
              type: "int",
              value: 0,
            },
            {
              name: "tileCol",
              type: "int",
              value: 1,
            },
          ],
          visible: true,
          rotation: 90,
        },
        {
          id: 2,
          width: 64,
          height: 64,
          gid: 18,
          type: "Endpoints.CFC.Warehouse.DEFAULT",
          name: "Endpoints.CFC.Warehouse.DEFAULT",
          x: 198.4,
          y: 66,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "left",
            },
            {
              name: "tileRow",
              type: "int",
              value: 0,
            },
            {
              name: "tileCol",
              type: "int",
              value: 2,
            },
          ],
          visible: true,
          rotation: 270,
        },
        {
          id: 3,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 296,
          y: 62.4,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "inTopLeft",
            },
            {
              name: "tileRow",
              type: "int",
              value: 0,
            },
            {
              name: "tileCol",
              type: "int",
              value: 4,
            },
          ],
          visible: true,
          rotation: 45,
        },
        {
          id: 4,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 424,
          y: 62.4,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "inTopLeft",
            },
            {
              name: "tileRow",
              type: "int",
              value: 0,
            },
            {
              name: "tileCol",
              type: "int",
              value: 6,
            },
          ],
          visible: true,
          rotation: 45,
        },
        {
          id: 5,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 552,
          y: 62.4,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "inTopLeft",
            },
            {
              name: "tileRow",
              type: "int",
              value: 0,
            },
            {
              name: "tileCol",
              type: "int",
              value: 8,
            },
          ],
          visible: true,
          rotation: 45,
        },
        {
          id: 6,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 20.799999999999997,
          y: 84.8,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "outTopRight",
            },
            {
              name: "tileRow",
              type: "int",
              value: 1,
            },
            {
              name: "tileCol",
              type: "int",
              value: 0,
            },
          ],
          visible: true,
          rotation: 135,
        },
        {
          id: 7,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 552,
          y: 126.4,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "inTopLeft",
            },
            {
              name: "tileRow",
              type: "int",
              value: 1,
            },
            {
              name: "tileCol",
              type: "int",
              value: 8,
            },
          ],
          visible: true,
          rotation: 45,
        },
        {
          id: 8,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 17.6,
          y: 174.4,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "top",
            },
            {
              name: "tileRow",
              type: "int",
              value: 2,
            },
            {
              name: "tileCol",
              type: "int",
              value: 0,
            },
          ],
          visible: true,
          rotation: 90,
        },
        {
          id: 9,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 148.8,
          y: 171.2,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "outTopLeft",
            },
            {
              name: "tileRow",
              type: "int",
              value: 2,
            },
            {
              name: "tileCol",
              type: "int",
              value: 2,
            },
          ],
          visible: true,
          rotation: 45,
        },
        {
          id: 10,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 302.4,
          y: 174.4,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "left",
            },
            {
              name: "tileRow",
              type: "int",
              value: 2,
            },
            {
              name: "tileCol",
              type: "int",
              value: 4,
            },
          ],
          visible: true,
          rotation: 0,
        },
        {
          id: 11,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 446.4,
          y: 152,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "inBottomLeft",
            },
            {
              name: "tileRow",
              type: "int",
              value: 2,
            },
            {
              name: "tileCol",
              type: "int",
              value: 6,
            },
          ],
          visible: true,
          rotation: 315,
        },
        {
          id: 12,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 529.6,
          y: 174.4,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "top",
            },
            {
              name: "tileRow",
              type: "int",
              value: 2,
            },
            {
              name: "tileCol",
              type: "int",
              value: 8,
            },
          ],
          visible: true,
          rotation: 90,
        },
        {
          id: 13,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 40,
          y: 382.4,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "inTopLeft",
            },
            {
              name: "tileRow",
              type: "int",
              value: 5,
            },
            {
              name: "tileCol",
              type: "int",
              value: 0,
            },
          ],
          visible: true,
          rotation: 45,
        },
        {
          id: 14,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 366.4,
          y: 337.6,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "bottom",
            },
            {
              name: "tileRow",
              type: "int",
              value: 5,
            },
            {
              name: "tileCol",
              type: "int",
              value: 5,
            },
          ],
          visible: true,
          rotation: 270,
        },
        {
          id: 15,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 529.6,
          y: 366.4,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "top",
            },
            {
              name: "tileRow",
              type: "int",
              value: 5,
            },
            {
              name: "tileCol",
              type: "int",
              value: 8,
            },
          ],
          visible: true,
          rotation: 90,
        },
        {
          id: 16,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 488,
          y: 446.4,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "inTopLeft",
            },
            {
              name: "tileRow",
              type: "int",
              value: 6,
            },
            {
              name: "tileCol",
              type: "int",
              value: 7,
            },
          ],
          visible: true,
          rotation: 45,
        },
        {
          id: 17,
          width: 32,
          height: 32,
          gid: 24,
          type: "Endpoints.House.Common.ORANGE",
          name: "Endpoints.House.Common.ORANGE",
          x: 148.8,
          y: 468.8,
          properties: [
            {
              name: "variant",
              type: "string",
              value: "outTopRight",
            },
            {
              name: "tileRow",
              type: "int",
              value: 7,
            },
            {
              name: "tileCol",
              type: "int",
              value: 2,
            },
          ],
          visible: true,
          rotation: 135,
        },
      ],
    },
    {
      x: 0,
      y: 0,
      width: 10,
      height: 8,
      opacity: 1,
      visible: true,
      name: "ObjectGroup.SCENERY",
      type: "objectgroup",
      draworder: "topdown",
      objects: [
        {
          id: 18,
          width: 64,
          height: 64,
          gid: 29,
          type: "Scenery.Building.SCHOOL",
          name: "Scenery.Building.SCHOOL",
          x: 424.88888888888886,
          y: 301.33333333333337,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 19,
          width: 64,
          height: 64,
          gid: 45,
          type: "Scenery.Other.SOLAR_PANEL",
          name: "Scenery.Other.SOLAR_PANEL",
          x: 320,
          y: 448.44444444444446,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 20,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: 371.5555555555555,
          y: -5.333333333333357,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 21,
          width: 64,
          height: 64,
          gid: 37,
          type: "Scenery.Nature.POND",
          name: "Scenery.Nature.POND",
          x: 524.4444444444445,
          y: 297.33333333333326,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 22,
          width: 64,
          height: 64,
          gid: 35,
          type: "Scenery.Nature.CROPS",
          name: "Scenery.Nature.CROPS",
          x: 249.33333333333331,
          y: 590.2222222222223,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 23,
          width: 64,
          height: 64,
          gid: 35,
          type: "Scenery.Nature.CROPS",
          name: "Scenery.Nature.CROPS",
          x: 363.1111111111111,
          y: 588.888888888889,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 24,
          width: 64,
          height: 64,
          gid: 35,
          type: "Scenery.Nature.CROPS",
          name: "Scenery.Nature.CROPS",
          x: 471.1111111111112,
          y: 591.1111111111111,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 25,
          width: 64,
          height: 64,
          gid: 35,
          type: "Scenery.Nature.CROPS",
          name: "Scenery.Nature.CROPS",
          x: 131.99999999999997,
          y: 583.1111111111111,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 26,
          width: 64,
          height: 64,
          gid: 35,
          type: "Scenery.Nature.CROPS",
          name: "Scenery.Nature.CROPS",
          x: 6.666666666666643,
          y: 579.1111111111109,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 27,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: -1.7777777777777786,
          y: -2.2222222222222214,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 28,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: 652.3333333333333,
          y: 89.16666666666666,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 29,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: 571,
          y: -4.5,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 30,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: 180,
          y: -4.666666666666657,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 31,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: -84,
          y: 70,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 32,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: 658.6666666666666,
          y: 210,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 33,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: 657.3333333333333,
          y: 340.6666666666667,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 34,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: 657.3333333333333,
          y: 472.6666666666667,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 35,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: -78.66666666666666,
          y: 467.3333333333333,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 36,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: -82.66666666666666,
          y: 342.00000000000006,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 37,
          width: 64,
          height: 64,
          gid: 39,
          type: "Scenery.Nature.Tree.PINE",
          name: "Scenery.Nature.Tree.PINE",
          x: -85.33333333333334,
          y: 226,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 38,
          width: 64,
          height: 64,
          gid: 35,
          type: "Scenery.Nature.CROPS",
          name: "Scenery.Nature.CROPS",
          x: 581.3333333333333,
          y: 591.3333333333335,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 39,
          width: 64,
          height: 64,
          gid: 34,
          type: "Scenery.Nature.BUSH",
          name: "Scenery.Nature.BUSH",
          x: 318.2222222222222,
          y: 144.4444444444444,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 40,
          width: 64,
          height: 64,
          gid: 34,
          type: "Scenery.Nature.BUSH",
          name: "Scenery.Nature.BUSH",
          x: 220.44444444444446,
          y: 316.8888888888889,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 41,
          width: 64,
          height: 64,
          gid: 34,
          type: "Scenery.Nature.BUSH",
          name: "Scenery.Nature.BUSH",
          x: 264,
          y: 253.77777777777774,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 42,
          width: 64,
          height: 64,
          gid: 34,
          type: "Scenery.Nature.BUSH",
          name: "Scenery.Nature.BUSH",
          x: 198.22222222222217,
          y: 425.3333333333332,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 43,
          width: 64,
          height: 64,
          gid: 34,
          type: "Scenery.Nature.BUSH",
          name: "Scenery.Nature.BUSH",
          x: 188.44444444444443,
          y: 168.44444444444443,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 44,
          width: 64,
          height: 64,
          gid: 26,
          type: "Scenery.Building.HOSPITAL",
          name: "Scenery.Building.HOSPITAL",
          x: 140.44444444444446,
          y: 292,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 45,
          width: 64,
          height: 64,
          gid: 27,
          type: "Scenery.Building.HOUSE",
          name: "Scenery.Building.HOUSE",
          x: 0.8888888888888857,
          y: 291.1111111111111,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 46,
          width: 64,
          height: 64,
          gid: 27,
          type: "Scenery.Building.HOUSE",
          name: "Scenery.Building.HOUSE",
          x: 118.28313038827079,
          y: 253.92622291443703,
          properties: [],
          visible: true,
          rotation: 177.00295741971627,
        },
        {
          id: 47,
          width: 64,
          height: 64,
          gid: 34,
          type: "Scenery.Nature.BUSH",
          name: "Scenery.Nature.BUSH",
          x: 320.88888888888886,
          y: 285.7777777777777,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 48,
          width: 64,
          height: 64,
          gid: 34,
          type: "Scenery.Nature.BUSH",
          name: "Scenery.Nature.BUSH",
          x: 576.8888888888888,
          y: 233.33333333333334,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 49,
          width: 64,
          height: 64,
          gid: 34,
          type: "Scenery.Nature.BUSH",
          name: "Scenery.Nature.BUSH",
          x: 587.5555555555555,
          y: 340,
          properties: [],
          visible: true,
          rotation: 0,
        },
        {
          id: 50,
          width: 64,
          height: 64,
          gid: 34,
          type: "Scenery.Nature.BUSH",
          name: "Scenery.Nature.BUSH",
          x: 56.888888888888886,
          y: 524.8888888888888,
          properties: [],
          visible: true,
          rotation: 0,
        },
      ],
    },
  ],
}

export interface LoadButtonProps
  extends Pick<ButtonItemProps, "isDrawerOpen"> {}

const LoadButton: FC<LoadButtonProps> = ({ isDrawerOpen }) => {
  const {
    ref: { current: phaserGame },
  } = usePhaserGameContext()

  return (
    <ButtonItem
      isDrawerOpen={isDrawerOpen}
      text="Load"
      icon={<CloudDownloadIcon />}
      // TODO: Fetch the level's Tiled JSON from the API instead of using the
      //  hardcoded example.
      onClick={() =>
        phaserGame?.setVariable("levelTiledJson", exampleLevelTiledJson)
      }
    />
  )
}

export default LoadButton
